include Makefile.common

all: complete build_assets

build_assets:
	if [ -d "assets" ]; then \
        python3 $(EMSDK)/upstream/emscripten/tools/file_packager.py web/assets.data --use-preload-plugins --preload assets@assets --js-output=web/assets.js; \
    fi
	if [ -d "tracks" ]; then \
        python3 $(EMSDK)/upstream/emscripten/tools/file_packager.py web/tracks.data --use-preload-plugins --preload tracks@tracks --js-output=web/tracks.js; \
    fi
	if [ -d "debug" ]; then \
        python3 $(EMSDK)/upstream/emscripten/tools/file_packager.py web/debug.data --use-preload-plugins --preload debug@debug --js-output=web/debug.js; \
    fi

clean_user:
	
PRISM_PATH = /mnt/c/DEV/PROJECTS/addons/prism
include ../addons/prism/Makefile.commonweb