name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write    

jobs:
  Linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y build-essential libreadline-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libglew-dev libpng-dev zip

      - name: External submodule (Prism)
        run: cd external/prism && make -f Makefile.linux

      - name: Continuous Integration
        run: make -f Makefile.linux

      - name: Build zip
        run: make -f Makefile.linux zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.zip