name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y build-essential libreadline-dev libsdl2-dev

      - name: External submodule (Prism)
        run: cd external/prism && make -f Makefile.linux

      - name: Continuous Integration
        run: make -f Makefile.linux